### ISSUE TITLE
ffmpeg version epoch

### ISSUE THREAD

**Issue by richhaynes** [jon-hedgerows/raspbian#1]
Hi Jon,

I have had an issue the past few days on trying to understand why I was getting a strange version of ffmpeg when installing get-iplayer from your repository. I've finally discovered that its down to a clash with using the deb-multimedia repository and the version epoch numbers of ffmpeg in both repositories.

For example, after using apt-get install get-iplayer, it requests to install ffmpeg but because I use deb-multimedia, I actually have two candidates for ffmpeg installation, as shown below:

```
$ apt-cache policy ffmpeg
ffmpeg:
  Installed: 10:2.6.9-dmo1
  Candidate: 10:2.6.9-dmo1
  Version table:
 *** 10:2.6.9-dmo1 0
        500 http://www.deb-multimedia.org/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
     7:3.2.2-1~bpo8+1.1 0
        500 http://packages.hedgerows.org.uk/raspbian/ jessie/ Packages
```
Now my first thoughts for hours were, 3.2.2 > 2.6.9 so why the heck is the wrong version getting installed?? Alot of research ensued and it turns out to be the version epoch number! Using both repositories, you epoch of 7 is lower than deb-multimedia's of 10, which in the apt world means that your package is considered the PREVIOUS version of the deb-multimedia package which is definitely not the case.

Since im new to this "epoch" world I was wondering, do you set the epoch number for your copy of ffmpeg or does this come from elsewhere? Can it be altered to account for a clash like this?

Clearly people are not shouting from the rooftops about this but I thought its an issue which should be highlighted just in case it pops up.

Simplest workaround it to designate the version to install using "apt-get install ffmpeg=7:3.2.2-1~bpo8+1.1" but this may then confuse users if they saw the message "The following packages will be DOWNGRADED: ffmpeg".

I hope this information can be helpful to you or others. I have also sent an email to the deb-multimedia maintainer to highlight this issue too.

Sources:
[http://man.he.net/man5/deb-version](url)
[http://askubuntu.com/questions/441879/why-do-some-packages-have-extra-numbers-on-the-front-of-their-version-string/441882#441882](url)
[https://www.debian.org/doc/debian-policy/ch-controlfields.html#fr36](url)

**Comment by jon-hedgerows** [comment]
So, very briefly for others who might come across this: the Epoch part of the version number (the bit before the colon) is used to cope with upstream version numbering doing odd things, like going backwards.  (Yeah, it happens once in a while ;-).  This allows a version number like "10:2.2" to be treated as newer than "7:3.1".  Sometimes that makes sense.

Here, specifically, the packages at packages.hedgerows.org.uk are derived from jessie-backports, and use the same epoch number as jessie-backports, which is 7:.  For reasons only they can explain, deb-multimedia use the epoch number 10:, which makes the deb-multimedia packages 'newer' than all earlier epochs, including 'newer' than jessie-backports.

packages.hedgerows.org.uk targets Raspbian, on /all/ versions of the Raspberry Pi (in theory), and the binaries are built to run on the Raspberry Pi [1] Model B, which has an ARMv6 processor.  These binaries are forward-compatible with ARMv7 (in the Pi 2) and ARMv8 (in the Pi 3) processors.

I believe that the packages hosted on deb-multimedia are targeted at the ARMv7, and they certainly don't run on a Pi 1.  (I tried!)

debian's architecture naming isn't terribly helpful either:  armel binaries use software floating point, and armhf binaries use hardware floating point - but nothing indicates whether it's an arm6, arm7 or arm8 architecture that's being targeted.  So you can't tell whether a binary built for "armhf" will actually work on your particular arm processor...

Recommendations:
* If you still use a raspberry pi 1, like I do, don't bother with deb-multimedia at all as it won't work for you.  Use ffmpeg from packages.hedgerows.org.uk
* If you use a raspberry pi 2 or 3, you may be able to use the official -backports repository for your version of debian (probably jessie-backports - and you'll want binaries for the armhf architecture), or use ffmpeg from packages.hedgerows.org.uk.
You may notice that I don't recommend deb-multimedia at all - this is because all the packages are out of date except for 'unstable', but your mileage may vary.

Following richhaynes' suggestion of explicitly downgrading ffmpeg to the version here will work fine, but will prevent ffmpeg from being upgraded in the future.

**Comment by richhaynes** [comment]
If I could I would ditch deb-multimedia right now as its caused me lots of problems over the years :( Therefore I second your recommendations! :)
